### ISSUE TITLE
Landscape crash

### ISSUE THREAD

**Issue by bahacan19** [moondroid/CoverFlow#1]
Samsung galaxy s3 on sample app
`
02-05 10:14:17.436  23085-23085/it.moondroid.coverflowdemo E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.IndexOutOfBoundsException: Invalid index 5, size is 4
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
            at java.util.ArrayList.get(ArrayList.java:308)
            at it.moondroid.coverflowdemo.CoverFlowActivity$1.onItemClick(CoverFlowActivity.java:39)
            at it.moondroid.coverflow.components.ui.containers.FeatureCoverFlow.handleClick(FeatureCoverFlow.java:955)
            at it.moondroid.coverflow.components.ui.containers.EndlessLoopAdapterContainer.onTouchEvent(EndlessLoopAdapterContainer.java:1106)
            at it.moondroid.coverflow.components.ui.containers.FeatureCoverFlow.dispatchTouchEvent(FeatureCoverFlow.java:1090)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2326)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1612)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2494)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2274)
            at android.view.View.dispatchPointerEvent(View.java:8025)
            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4668)
            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4556)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4150)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4207)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4176)
            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4261)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4184)
            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4318)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4150)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4207)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4176)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4184)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4150)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6302)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6240)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6211)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6382)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:188)
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java:132)
            at android.os.Looper.loop(Looper.java:138)
            at android.app.ActivityThread.main(ActivityThread.java:5419)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
            at dalvik.system.NativeStart.main(Native Method)`

**Comment by javakias** [comment]
It seems like the error is in the Adapter. You should check the getView method again.
