### ISSUE TITLE
Crash with start with custom layout

### ISSUE THREAD

**Issue by AythamiIHS** [moondroid/CoverFlow#4]
Hi,
 when I use this library with custom layout, this crash. with this error
4-08 15:50:29.265  27655-27655/com.intrahouse.deck2play E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.ArithmeticException: divide by zero
            at it.moondroid.coverflow.components.ui.containers.FeatureCoverFlow.dispatchDraw(FeatureCoverFlow.java:471)
            at android.view.View.getDisplayList(View.java:13739)
            at android.view.View.getDisplayList(View.java:13786)
            at android.view.View.draw(View.java:14563)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3316)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3153)
            at android.view.View.getDisplayList(View.java:13739)
            at android.view.View.getDisplayList(View.java:13786)
            at android.view.View.draw(View.java:14563)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3316)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3153)
            at android.view.View.getDisplayList(View.java:13739)
            at android.view.View.getDisplayList(View.java:13786)
            at android.view.View.draw(View.java:14563)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3316)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3153)
            at android.view.View.getDisplayList(View.java:13739)
            at android.view.View.getDisplayList(View.java:13786)
            at android.view.View.draw(View.java:14563)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3316)
            at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1060)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3153)
            at android.view.View.getDisplayList(View.java:13739)
            at android.view.View.getDisplayList(View.java:13786)
            at android.view.View.draw(View.java:14563)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3316)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3153)
            at android.view.View.draw(View.java:14856)
            at android.widget.FrameLayout.draw(FrameLayout.java:467)
            at android.view.View.getDisplayList(View.java:13744)
            at android.view.View.getDisplayList(View.java:13786)
            at android.view.View.draw(View.java:14563)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3316)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3153)
            at android.view.View.draw(View.java:14856)
            at android.widget.FrameLayout.draw(FrameLayout.java:467)
            at android.view.View.getDisplayList(View.java:13744)
            at android.view.View.getDisplayList(View.java:13786)
            at android.view.View.draw(View.java:14563)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3316)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3153)
            at android.view.View.getDisplayList(View.java:13739)
            at android.view.View.getDisplayList(View.java:13786)
            at android.view.View.draw(View.java:14563)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3316)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3153)
            at android.view.View.getDisplayList(View.java:13739)
            at android.view.View.getDisplayList(View.java:13786)
            at android.view.View.draw(View.java:14563)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3316)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3153)
            at android.view.View.getDisplayList(View.java:13739)
            at android.view.View.getDisplayList(View.java:13786)
            at android.view.View.draw(View.java:14563)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3316)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3153)
            at android.view.View.draw(View.java:14856)
            at android.widget.FrameLayout.draw(FrameLayout.java:467)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2621)
            at android.view.View.getDisplayList(View.java:13744)
            at android.view.View.getDisplayList(View.java:13786)
            at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1411)
            at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1359)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2672)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2538)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2154)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1249)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6364)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
            at android.v

The code is similar to the example

**Comment by kibotu** [comment]
check if all your images are correctly allocated when passing them to the coverflow
