### ISSUE TITLE
null pointer exception

### ISSUE THREAD

**Issue by bakbanga** [moondroid/CoverFlow#7]
java.lang.Throwable: addFocusables
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3093)
            at it.moondroid.coverflow.components.ui.containers.FeatureCoverFlow.dispatchDraw(FeatureCoverFlow.java:454)
            at android.view.View.draw(View.java:14908)
            at android.view.View.getDisplayList(View.java:13724)
            at android.view.View.getDisplayList(View.java:13771)
            at android.view.View.draw(View.java:14599)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
            at android.view.View.draw(View.java:14908)
            at android.view.View.getDisplayList(View.java:13724)
            at android.view.View.getDisplayList(View.java:13771)
            at android.view.View.draw(View.java:14599)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
            at android.view.View.draw(View.java:14908)
            at android.view.View.getDisplayList(View.java:13724)
            at android.view.View.getDisplayList(View.java:13771)
            at android.view.View.draw(View.java:14599)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
            at android.view.View.getDisplayList(View.java:13716)
            at android.view.View.getDisplayList(View.java:13771)
            at android.view.View.draw(View.java:14599)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
            at android.view.View.draw(View.java:14908)
            at android.widget.FrameLayout.draw(FrameLayout.java:534)
            at android.view.View.getDisplayList(View.java:13724)
            at android.view.View.getDisplayList(View.java:13771)
            at android.view.View.draw(View.java:14599)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
            at android.view.View.draw(View.java:14908)
            at android.view.View.getDisplayList(View.java:13724)
            at android.view.View.getDisplayList(View.java:13771)
            at android.view.View.draw(View.java:14599)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
            at android.view.View.draw(View.java:14908)
            at android.widget.FrameLayout.draw(FrameLayout.java:534)
            at android.view.View.getDisplayList(View.java:13724)
            at android.view.View.getDisplayList(View.java:13771)
            at android.view.View.draw(View.java:14599)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
            at android.view.View.draw(View.java:14908)
            at android.view.View.getDisplayList(View.java:13724)
            at android.view.View.getDisplayList(View.java:13771)
            at android.view.View.draw(View.java:14599)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2416)
            at android.view.View.draw(View.java:14908)
            at android.widget.FrameLayout.draw(FrameLayout.java:534)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2396)
            at android.view.View.getDisplayList(View.java:13724)
            at android.view.View.getDisplayList(View.java:13771)
            at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1627)
            at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1506)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2728)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2593)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2216)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1192)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6231)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:816)
            at android.view.Choreographer.doCallbacks(Choreographer.java:619)
            at android.view.Choreographer.doFrame(Choreographer.java:588)

**Comment by kernelheart** [comment]
Hi, did you find solution ?

**Comment by anselm94** [comment]
Verify if your CoverFlowAdapter isn't null.
